config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      registrations: 'users/registrations',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :courses, except: [:edit] do # Edit реализован через Wizard
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    resources :lessons do
      put :sort
      resources :comments
      member do
        delete :delete_video
      end
    end
    resources :enrollments, only: [:new, :create, :index]

    member do
      get :analytics
      patch :approve
      patch :unapprove
    end
    resources :course_wizard, controller: 'courses/course_wizard'
  end

  resources :users, only: [:index, :edit, :show, :update]
  resources :youtube, only: :show
  resources :tags, only: [:create, :index, :destroy]


  resources :enrollments do
    get :my_students, on: :collection
    member do
      get :certificate
    end
  end

  get 'home/index'
  get 'analytics', to: 'home#analytics'
  get 'privacy_policy', to: 'home#privacy_policy'

  namespace :charts do
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'money_makers'
  end

  get 'activity', to: 'home#activity'
  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :privacy_policy]

  def index
    @courses = Course.all.limit(3)
    @latest_good_reviews = Enrollment.reviewed.latest_good_reviews
    @latest = Course.latest.published.approved
    @top_rated = Course.top_rated.published.approved
    @popular = Course.popular.published.approved
    @purchased_courses = Course.joins(:enrollments).where(enrollments: { user: current_user }).order(created_at: :desc).limit(3)
    @latest_courses = Course.all.limit(3).order(created_at: :desc)
    @popular_tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc).limit(10)
  end

  def activity
    if current_user.has_role?(:admin)
      @pagy, @activities = pagy(PublicActivity::Activity.all.order(created_at: :desc))
    else
      redirect_to root_path, alert: 'You are not authorized to access this page'
    end
  end

  def analytics
    if current_user.has_role?(:admin)
    else
      redirect_to root_path, alert: 'You are not authorized to access this page'
    end
  end

  def privacy_policy
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/activity.html.haml
- content_for :title do
  University
  \|
  Activity

%h3
  .text-center
    Activity
    .badge.badge-info
      = @activities.count
%p
!= pagy_bootstrap_nav(@pagy)
%ul.list-group
  - @activities.each do |activity|
    %li.list-group-item
      = activity.created_at.strftime('%d-%m-%Y %H:%M')
      (#{ time_ago_in_words(activity.created_at) })
      = model_label(activity.trackable_type)
      - if activity.trackable_type == 'Lesson'
        - if Lesson.where(id: activity.trackable_id).present?
          = link_to activity.trackable, course_lesson_path(activity.trackable.course, activity.trackable)
        - else
          Lesson was deleted

      - elsif activity.trackable_type == "Comment"
        - if Comment.where(id: activity.trackable_id).present?
          = link_to activity.trackable.content, course_lesson_path( activity.trackable.lesson.course, activity.trackable.lesson)
        - else
          Comment was deleted

      - else
        = link_to activity.trackable, activity.trackable
      |
      = activity.key
      = crud_label(activity.key.match(/\.(.*)/)[1])
      by
      = link_to activity.owner, user_path(activity.owner)
      - if activity.parameters.any?
        = activity.parameters
%p
!= pagy_bootstrap_nav(@pagy)

app/views/home/analytics.html.haml
- content_for :title do
  University
  \|
  Analytics

%h3
  .text-center
    = action_name.humanize


.card
  %h4.text-center
    Users created
  .card-body
    = line_chart charts_users_per_day_path
  %br
  %h4.text-center
    Enrollment created
  .card-body
    = column_chart charts_enrollments_per_day_path
  %br
  %h4.text-center
    Course popularity
  .card-body
    = bar_chart charts_course_popularity_path

  %br
  %h4.text-center
    Most paid courses
  .card-body
    = bar_chart charts_money_makers_path

app/views/home/index.html.haml
- content_for :title do
  University
  \|
  Online Courses - Learn Anything, On Your Schedule

.jumbotron.shadow.parallax
  %h1.text-shadow
    %b What do you want to learn today?
  .p-4

  - if current_user
    .p-3
    = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
      .input-group
        = f.search_field :title_cont, class: 'form-control-lg', style: 'float: left; width: 200px; ', placeholder: 'Find a course', :autocomplete => :off
        %span.input-group-append
          %button.btn.btn-primary.btn-lg{:type => "submit"}
            %span.fa.fa-search{"aria-hidden" => "true"}
    .p-2
  - else
    %h3.text-shadow Join to access all the courses
    .p-2
    = link_to 'Register', new_user_registration_path, class: 'btn btn-custom-purple btn-lg'
    = link_to 'Login', new_user_session_path, class: 'btn btn-custom-purple btn-lg'
    .row.mt-1
    = link_to user_google_oauth2_omniauth_authorize_path, class: 'btn btn-danger btn-lg mr-1' do
      Continue with
      .fab.fa-google
    .row.mt-1
    = link_to user_github_omniauth_authorize_path, class: 'btn btn-dark btn-lg mr-1' do
      Continue with
      .fab.fa-github
    .row.mt-1
    = link_to user_facebook_omniauth_authorize_path, class: 'btn btn-primary btn-lg mr-1' do
      Continue with
      .fab.fa-facebook

.card-group

  .card.card-body
    %h1
      .fa.fa-graduation-cap
    = Course.count
    online courses
    .row
    Explore a variety of fresh topics

  .card.card-body
    %h1
      .fa.fa-chalkboard-teacher
      /.fa.fa-brain
    = Course.distinct.count(:user_id)
    expert instructors
    .row
    Find the right instructor for you
  .card.card-body
    %h1
      .fa.fa-user-graduate
    = User.count
    active learners
    .row
    Join the knowledge sharing community
  .card.card-body
    %h1
      .fa.fa-infinity
    Lifetime access
    .row
    Learn on your schedule
%hr
  %small На почтовую рассылку стоит заглушка ( при регистрации, подтверждении)
  %p Test users:
  %p admin@admin.ru 123456
  %p user1@test.ru  123456
  = link_to url_for("https://github.com/sasha370/universitetHQ") do
    GitHub repo

%hr
- if current_user
  %h2
    .fa.fa-graduation-cap
    Continue learning
  .card-columns
    - @purchased_courses.each do |course|
      = render 'courses/course', course: course
  .text-right
    = link_to "All my purchased courses ", purchased_courses_path
%hr
%h2
  .fa.fa-chart-line
  Popular courses
.card-columns
  - @popular.each do |course|
    = render 'courses/course', course: course
  .text-right
    = link_to "More popular courses", courses_path(courses_search: {s: 'enrollments_count desc'})

%hr
%h2
  .fa.fa-star
  Top rated courses
.card-columns
  - @top_rated.each do |course|
    = render 'courses/course', course: course
  .text-right
    = link_to "More best rated courses", courses_path(courses_search: {s: 'average_rating desc'})
%hr
%h2
  .fa.fa-clock
  Latest courses

.card-columns
  - @latest.each do |course|
    = render 'courses/course', course: course
  .text-right
    = link_to "More new courses", courses_path(courses_search: {s: 'created_at desc'})

%hr
%h3
  .fa.fa-tags
  Popular Tags
- @popular_tags.each do |tag|
  = link_to courses_path(courses_search: {course_tags_tag_id_eq: tag.id}) do
    .badge.badge-info
      %h5
        = tag.name
        .badge.badge-light
          = tag.course_tags_count

%h2
  .fa.fa-comment
    What our student have to say
.card-columns
  - @latest_good_reviews.each do |enrollment|
    = render 'enrollments/enrollment', enrollment: enrollment

app/views/home/privacy_policy.html.haml
%h2 Privacy Policy
%p
  Your privacy is important to us. It is University's policy to respect your privacy regarding any information we may collect from you across our website,
  = succeed "," do
    %a{:href => "http://university.budka52.ru"} http://university.budka52.ru
%p We only ask for personal information when we truly need it to provide a service to you. We collect it by fair and lawful means, with your knowledge and consent. We also let you know why we’re collecting it and how it will be used.
%p We only retain collected information for as long as necessary to provide you with your requested service. What data we store, we’ll protect within commercially acceptable means to prevent loss and theft, as well as unauthorized access, disclosure, copying, use or modification.
%p We don’t share any personally identifying information publicly or with third-parties, except when required to by law.
%p Our website may link to external sites that are not operated by us. Please be aware that we have no control over the content and practices of these sites, and cannot accept responsibility or liability for their respective privacy policies.
%p You are free to refuse our request for your personal information, with the understanding that we may be unable to provide you with some of your desired services.
%p Your continued use of our website will be regarded as acceptance of our practices around privacy and personal information. If you have any questions about how we handle user data and personal information, feel free to contact us.
%p This policy is effective as of 24 April 2020.