config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      registrations: 'users/registrations',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :courses, except: [:edit] do # Edit реализован через Wizard
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    resources :lessons do
      put :sort
      resources :comments
      member do
        delete :delete_video
      end
    end
    resources :enrollments, only: [:new, :create, :index]

    member do
      get :analytics
      patch :approve
      patch :unapprove
    end
    resources :course_wizard, controller: 'courses/course_wizard'
  end

  resources :users, only: [:index, :edit, :show, :update]
  resources :youtube, only: :show
  resources :tags, only: [:create, :index, :destroy]


  resources :enrollments do
    get :my_students, on: :collection
    member do
      get :certificate
    end
  end

  get 'home/index'
  get 'analytics', to: 'home#analytics'
  get 'privacy_policy', to: 'home#privacy_policy'

  namespace :charts do
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'money_makers'
  end

  get 'activity', to: 'home#activity'
  root 'home#index'
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course, counter_cache: true
  validates :title, :content, :course, presence: true
  validates :title, length: {maximum: 70}
  validates_uniqueness_of :title, scope: :course
  has_many :user_lessons, dependent: :destroy
  has_many :comments, dependent: :nullify

  has_rich_text :content

  has_one_attached :video
  has_one_attached :video_thumbnail
  validates :video, content_type: ['video/mp4'],
            size: { less_than: 50.megabytes, message: "image must be less that 50 MB" }
  validates :video_thumbnail,content_type: [:png, :jpg, :jpeg],
            size: { less_than: 500.kilobytes, message: "image must be less that 500 Kb" }

  extend FriendlyId
  friendly_id :title, use: :slugged

  include PublicActivity::Model
  tracked owner: Proc.new { |controller, model| controller.current_user }

  include RankedModel
  ranks :row_order, :with_same => :course_id


  def to_s
    title
  end

  def prev
    course.lessons.where("row_order < ?", row_order).order(:row_order).last
  end

  def next
    course.lessons.where("row_order > ?", row_order).order(:row_order).first
  end

  def viewed(user)
    self.user_lessons.where(user: user).present?
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy, :delete_video]

  def delete_video
    authorize @lesson, :edit?
    @lesson.video.purge
    @lesson.video_thumbnail.purge
    redirect_to edit_course_lesson_path(@course,@lesson), notice: "Video Deleted!"
  end

  def sort
    @course = Course.friendly.find(params[:course_id])
    lesson = Lesson.friendly.find(params[:lesson_id])
    authorize lesson, :edit?
    lesson.update(lesson_params)
    render body: nil
  end

  def index
    @lessons = Lesson.all
  end

  def show
    authorize @lesson
    current_user.view_lesson(@lesson)
    @lessons = @course.lessons.rank(:row_order)
    @comment = Comment.new
    @comments = @lesson.comments.order(created_at: :desc)
  end

  def new
    @lesson = Lesson.new
    @course = Course.friendly.find(params[:course_id])
  end

  def edit
    authorize @lesson
    @course = Course.friendly.find(params[:course_id])
  end

  def create
    @lesson = Lesson.new(lesson_params)
    @course = Course.friendly.find(params[:course_id])
    @lesson.course_id = @course.id
    authorize @lesson
    respond_to do |format|
      if @lesson.save
        format.html { redirect_to course_lesson_url(@course, @lesson), notice: 'Lesson was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    authorize @lesson
    @course = Course.friendly.find(params[:course_id])
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to course_lesson_url(@course, @lesson), notice: 'Lesson was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    authorize @lesson
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to course_url(@course), notice: 'Lesson was successfully destroyed.' }
    end
  end

  private
    def set_lesson
      @course = Course.friendly.find(params[:course_id])
      @lesson = Lesson.friendly.find(params[:id])
    end

    def lesson_params
      params.require(:lesson).permit(:title, :content, :row_order_position, :video, :video_thumbnail)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.haml
= simple_form_for([@course, @lesson]) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title, input_html: {autocomplete: 'off'}
    = f.input :content, as: :rich_text_area
    %p
    = f.input :video
    - if @lesson.video.attached?
      = @lesson.video.filename
      .row
      = link_to "Remove video and thumbnail", delete_video_course_lesson_path(@course, @lesson), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-danger'
    %p
    = f.input :video_thumbnail
    - if @lesson.video_thumbnail.attached?
      = image_tag @lesson.video_thumbnail
      .row
      = @lesson.video_thumbnail.filename

  %p
  .form-actions
    = f.button :submit

app/views/lessons/_lesson.html.haml
.card
  .card-header
    - if lesson.viewed(current_user)
      .text-success.far.fa-check-square
    -else
      .text-danger.far.fa-check-square

    = link_to course_lesson_path(@course, lesson) do
      %b
        #{lesson.row_order_rank + 1}.
      = lesson.title

  .card-body
    - if lesson.video.attached?
      - if lesson.video_thumbnail.attached?
        %video(controls="true" poster="#{url_for lesson.video_thumbnail}" width="100%" preload="metadata" controlslist="nodownload")
          %source{src: rails_blob_url(lesson.video), type:"#{lesson.video.content_type}"}
      - else
        %video(controls="true"  width="100%" preload="metadata" controlslist="nodownload")
          %source{src: rails_blob_url(lesson.video), type:"#{lesson.video.content_type}"}
    = lesson.content
  - if policy(lesson).edit?
    .card-footer
      = link_to 'Edit', edit_course_lesson_path(@course, lesson), class: 'btn btn-sm btn-outline-warning'
      = link_to 'Destroy', [@course, lesson], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-danger'

    .card-footer
      - if lesson.prev.present?
        .float-left
          = link_to course_lesson_path(@course, lesson.prev), class: 'btn btn-sm btn-info' do
            .fa.fa-arrow-left
            Previous

      - if  lesson.next.present?
        .float-right
          = link_to course_lesson_path(@course, lesson.next), class: 'btn btn-sm btn-info' do
            .fa.fa-arrow-right
            Next

app/views/lessons/_lesson_preview.html.haml
- if current_user
  - if lesson.viewed(current_user)
    .text-success.far.fa-check-square
  -else
    .text-danger.far.fa-check-square
    .fa.fa-lock
  = link_to course_lesson_path(@course, lesson) do
    %b
      #{lesson.row_order_rank + 1}.
    = lesson.title
- else
  .fa.fa-lock
    = link_to course_lesson_path(@course, lesson) do
      %b
        #{lesson.row_order_rank + 1}.
      = lesson.title

.float-right

  .fa.fa-comment
  = lesson.comments_count
  - if policy(lesson).edit?
    .fa.fa-eye
    Impressions:
    = lesson.user_lessons.map(&:impressions).sum
    .fa.fa-eye
    Unique:
    = lesson.user_lessons_count
    = link_to 'Edit', edit_course_lesson_path(@course, lesson), class: 'btn btn-sm btn-outline-warning'
    = link_to 'Destroy', [@course, lesson], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-danger'

app/views/lessons/edit.html.haml
- content_for :title do
  University
  \|
  = @course.title
  \/
  Edit
  = @lesson.title

= link_to 'Courses', courses_path
\/
= link_to @lesson.course.title, course_path(@lesson.course)
\/
= link_to @lesson.title, course_lesson_path(@course, @lesson)
\/
Edit
%p

.card
  .card-header
    %h3
      .far.fa.fa-check-square
      Editing lesson
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Show', course_lessons_path(@course, @lesson)
    \|
    = link_to 'Back to course', course_path(@lesson.course)

app/views/lessons/new.html.haml
- content_for :title do
  University
  \|
  = @course.title
  \/
  New lesson

= link_to 'Courses', courses_path
\/
= link_to @course, course_path(@course)
\/
New
%p
.card
  .card-header
    %h3
      .far.fa.fa-check-square
      New lesson
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Back to course', course_path(@course)

app/views/lessons/show.html.haml
- content_for :title do
  University
  \|
  = @course.title
  \/
  = @lesson.title

= link_to 'Courses', courses_path
\/
= link_to  course_path(@lesson.course) do
  .fa.fa-graduation-cap
  = @lesson.course.title
\/
= link_to  course_lesson_path(@course, @lesson) do
  .fa.fa-check-square
  = @lesson.title
%p

.row
  .col-lg-8
    = render 'lessons/lesson', lesson: @lesson
    %p
    %h4
      .fa.fa-comment
      Comments
      = @lesson.comments_count
    .card
      .card-header
        New comment:
      .card-body
        = render 'lessons/comments/form'
    %p
    - @comments.each do |comment|
      = render 'lessons/comments/comment', comment: comment
      %p


  .col-lg-4
    %ul.list-group
      %li.list-group-item
        = link_to  course_path(@lesson.course) do
          .fa.fa-graduation-cap
          = @lesson.course.title
        .row
        .fa.fa-spinner
        = number_to_percentage(@course.progress(current_user), precision: 0)
      - @lessons.each do |lesson|
        - if lesson ==@lesson
          %li.list-group-item.list-group-item-success
            =  render "lessons/lesson_preview",  lesson: lesson
        - else
          %li.list-group-item
            =  render "lessons/lesson_preview",  lesson: lesson

  = link_to 'Back to course', course_path(@lesson.course)