config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      registrations: 'users/registrations',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :courses, except: [:edit] do # Edit реализован через Wizard
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    resources :lessons do
      put :sort
      resources :comments
      member do
        delete :delete_video
      end
    end
    resources :enrollments, only: [:new, :create, :index]

    member do
      get :analytics
      patch :approve
      patch :unapprove
    end
    resources :course_wizard, controller: 'courses/course_wizard'
  end

  resources :users, only: [:index, :edit, :show, :update]
  resources :youtube, only: :show
  resources :tags, only: [:create, :index, :destroy]


  resources :enrollments do
    get :my_students, on: :collection
    member do
      get :certificate
    end
  end

  get 'home/index'
  get 'analytics', to: 'home#analytics'
  get 'privacy_policy', to: 'home#privacy_policy'

  namespace :charts do
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'money_makers'
  end

  get 'activity', to: 'home#activity'
  root 'home#index'
end

app/controllers/courses/course_wizard_controller.rb
class Courses::CourseWizardController < ApplicationController
  include Wicked::Wizard

  before_action :set_progress, only: [:show, :update]
  before_action :set_course, only: [:show, :update, :finish_wizard_path]
  steps :basic_info, :details, :lessons, :publish

  def show
    authorize @course, :edit?
    case step
      when :basic_info
      when :details
        @tags = Tag.all
      when :lessons
        unless @course.lessons.any?
          @course.lessons.build
        end
      when :publish

    end
    render_wizard
  end

  def update
    authorize @course, :edit?
    @course.update_attributes(course_params)
    case step
      when :basic_info
      when :details
        @tags = Tag.all
      when :lessons
      when :publish
    end
    render_wizard @course
  end

  def finish_wizard_path
    authorize @course, :edit?
    course_path(@course)
  end

  private

  def set_progress
    if wizard_steps.any? && wizard_steps.index(step).present?
      @progress = ((wizard_steps.index(step) + 1).to_d / wizard_steps.count.to_d) * 100
    else
      @progress = 0
    end
  end

  def set_course
    @course = Course.friendly.find(params[:course_id])
  end

  def course_params
    params.require(:course).permit(:title, :description, :marketing_description, :price, :level, :language, :published,
                                   :avatar, tag_ids: [],  lessons_attributes: [:id, :title, :content, :_destroy])
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy, :approve, :unapprove, :analytics]
  skip_before_action :authenticate_user!, only: [:show]

  def index
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    @ransack_path = courses_path
    @ransack_courses = Course.published.approved.ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user, :course_tags, :course_tags => :tag))
  end

  def purchased
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    @ransack_path = purchased_courses_path
    @ransack_courses = Course.joins(:enrollments).where(enrollments: { user: current_user }).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user))
    render :index
  end

  def pending_review
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    @ransack_path = pending_review_courses_path
    @ransack_courses = Course.joins(:enrollments).merge(Enrollment.pending_review.where(user: current_user)).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user))
    render :index
  end

  def created
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    @ransack_path = created_courses_path
    @ransack_courses = Course.where(user: current_user).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user))
    render :index
  end

  def analytics
    authorize @course, :owner?
  end

  def approve
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    authorize @course, :approve?
    @course.update_attribute(:approved, true)
    redirect_to unapproved_courses_path, notice: "Course Approved!"
  end

  def unapprove
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    authorize @course, :approve?
    @course.update_attribute(:approved, false)
    redirect_to unapproved_courses_path, notice: "Course Unapproved and hidden!"
  end

  def unapproved
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    @ransack_path = unapproved_courses_path
    @ransack_courses = Course.unapproved.ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user))
    render :index
  end

  def show
    authorize @course
    @lessons = @course.lessons.rank(:row_order).all
    @enrollments_with_reviews = @course.enrollments.reviewed
    @courses = []
    Course.all.where.not(id: @course.id).each do |course|
      if @course.tags.pluck(:id).intersection(course.tags.pluck(:id)).count > 0
        @courses.push(course)
      end
    end
  end

  def new
    @course = Course.new
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    authorize @course
  end

  def create
    @course = Course.new(course_params)
    @course.description = "Curriculum Description"
    @course.marketing_description = "Marketing Description"

    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    authorize @course
    @course.user = current_user

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_course_wizard_index_path(@course), notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @course
    if @course.destroy
      respond_to do |format|
        format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      end
    else
      redirect_to @course, alert: "Course has enrollments. Can not be destroyed"
    end
  end

  private

  def set_course
    @course = Course.friendly.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :description, :marketing_description, :price, :level, :language, :published, :avatar, tag_ids: [])
  end
end

app/helpers/courses_helper.rb
module CoursesHelper

  def enrollment_button(course)
    if current_user
      if course.user == current_user
        link_to "You created this course. View analitics", course_path(course)
      elsif course.enrollments.where(user: current_user).any?
        link_to course_path(course) do
          "<i class='fa fa-spinner'></i>".html_safe + " " +
              number_to_percentage(course.progress(current_user), precision: 0)
        end
      elsif course.price > 0
        link_to number_to_currency(course.price), new_course_enrollment_path(course), class: 'btn btn-success'
      else
        link_to 'Free', new_course_enrollment_path(course), class: 'btn btn-success'
      end
    else
      link_to "Check price", new_course_enrollment_path(course), class: 'btn btn-ms btn-success'
    end
  end

  def review_button(course)
    user_course = course.enrollments.where(user: current_user)
    if current_user
      if user_course.any?
        if user_course.pending_review.any?
          link_to edit_enrollment_path(user_course.first) do
            "<i class='text-warning fa fa-star'></i>".html_safe + " " +
                "<i class='text-dark fa fa-question'></i>".html_safe + " " +
                "Add a review"
          end
        else
          link_to enrollment_path(user_course.first) do
            "<i class='text-warning fa fa-star'></i>".html_safe + " " +
                "<i class='fa fa-check'></i>".html_safe + " " +
                "Thanks for Review"
          end
        end
      end
    end
  end

  def certificate_button(course)
    user_course = course.enrollments.where(user: current_user)
    if current_user
      if user_course.any?
        if @course.progress(current_user) == 100
          link_to  certificate_enrollment_path( user_course.first, format: :pdf), class: 'btn btn-sm btn-success' do
          "<i class='fa fa-file-pdf'></i>".html_safe + " " +
              "Certificate от Completion"
          end
        else
          "Certificate available after completion"
        end
      end
    end
  end
end

app/views/courses/_course.html.haml
.card
  .card-header
    .fa.fa-graduation-cap
    = link_to course.title, course_path(course)
  - if course.avatar.attached?
    .card-img-top
      = image_tag course.avatar, width:  "100%"

  .card-body
    %small= simple_format(course.marketing_description)
  .card-footer
    .text-center
      = enrollment_button(course)
      .row
      = review_button(course)

  .card-footer
    .row
      .col-md-6
        .text-warning.fa.fa-star
        = course.average_rating
        (
        .fa.fa-user-graduate
        = course.enrollments_count
        )
        .fa.fa-tasks
          = course.lessons_count
      .col-md-6.text-right
        .fa.fa-chalkboard-teacher
        = link_to course.user.username, user_path(course.user)

  - if current_user
    - if policy(course).owner?
      .card-footer
        = link_to  new_course_lesson_path(course, @lesson), class: "btn btn-outline-primary btn-sm " do
          Add lesson
        = link_to  course_course_wizard_index_path(course), class: "btn btn-sm btn-outline-warning mr-1" do
          .fa.fa-edit
          Edit
        - if policy(course).destroy?
          = link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-danger"
        = link_to analytics_course_path(course), class: 'btn btn-sm btn-outline-info mt-1' do
          .fa.fa-chart-bar
          Analytics

    - if policy(course).admin_or_owner?
      .card-footer
        - if course.published?
          .badge.badge-success Published
        -else
          .badge.badge-danger Unpublished
        - if course.approved?
          .badge.badge-success Approved
        -else
          .badge.badge-danger Unapproved
        - if policy(course).approve?
          - if course.approved?
            = link_to "Unapprove", unapprove_course_path(course), method: :patch, class: "btn btn-sm btn-outline-danger"
          -else
            = link_to "Approve", approve_course_path(course), method: :patch, class: "btn btn-sm btn-outline-success"

      .card-footer
        - course.tags.each do |tag|
          .badge.badge-info
            = tag.name

app/views/courses/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@course) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title, input_html: {autocomplite: 'off'}

  .form-actions
    = f.button :submit

app/views/courses/analytics.html.haml
- content_for :title do
  University
  \|
  = @course.title
  Analytics

= link_to 'Courses', courses_path
\/
= link_to course_path(@course) do
  .fa.fa-graduation-cap
  = @course.title
\/
= link_to analytics_course_path(@course) do
  .fa.fa-chart-bar
  Analytics

%h4.text-center
  Analytics for #{@course.title}
%p
Enrollments per day, quantity
= line_chart  @course.enrollments.group_by_day(:created_at).count

Enrollments per day, revenue
= line_chart  @course.enrollments.group_by_day(:created_at).sum(:price)

Impressions per lesson ( how many times the lesson was viewed)
= bar_chart @course.user_lessons.joins(:lesson).group(:'lessons.title').sum(:impressions)

Unique user views (how many unique users viewed the lesson)
= bar_chart @course.user_lessons.joins(:lesson).group(:'lessons.title').count

app/views/courses/edit.html.haml
- content_for :title do
  University
  \|
  Edit
  = @course.title

= link_to 'Courses/', courses_path
= link_to @course.title, course_path(@course)

.card
  .card-body
    %h3
      .fa.fa-graduation-cap
        Edit course
  .card-body
    = render 'form'

= link_to 'Show', @course
\|
= link_to 'Back', courses_path

app/views/courses/index.html.haml
- content_for :title do
  University
  \|
  = action_name.humanize
  сourses

%h3
  .text-center
    = action_name.humanize
    courses
    .badge.badge-info
      = @courses.count
%p
.row
  .col-md-2
    = search_form_for @ransack_courses, as: :courses_search, url: @ransack_path  do |f|
      = f.label :title,  class: "col-form-label"
      = f.search_field :title_cont, placeholder: "Title", class: "form-control form-control-sm"
      = f.label :tag, class: "col-form-label"
      = f.search_field :course_tags_tag_name_cont, placeholder: "Tag name", class: "form-control form-control-sm"
      = f.label :description,  class: "col-form-label"
      = f.search_field :marketing_description_cont, placeholder: "Short-description", class: "form-control form-control-sm"
      = f.label :language,  class: "col-form-label"
      = f.select :language_cont,  Course.languages,  include_blank: true
      = f.label :level,  class: "col-form-label"
      = f.select :level_cont,  Course.levels, include_blank: true
      = f.search_field :price_eq, placeholder: "Price", class: "form-control form-control-sm"
      = f.label :teacher,  class: "col-form-label"
      = f.search_field :user_email_cont, placeholder: "User Email", class: "form-control form-control-sm"
      .row
      = sort_link(@ransack_courses, :price )
      .row
      = sort_link(@ransack_courses, :average_rating, "Top rating" )
      .row
      = sort_link(@ransack_courses, :enrollments_count, " Most popular" )
      .row
      = sort_link(@ransack_courses, :created_at, "Fresh" )
      .row
      = f.submit
    = link_to @ransack_path, class: 'btn btn-sm btn-secondary' do
      .fa.fa-sync

    .row
    - @tags.each do |tag|
      = link_to controller: controller_name, action: action_name,  courses_search: {course_tags_tag_id_eq: tag.id} do
        .badge.badge-info
          = tag.name
          .badge.badge-light
            = tag.course_tags_count


  .col-md-10
    != pagy_bootstrap_nav(@pagy)
    .card-columns
      - @courses.each do |course|
        = render 'courses/course', course: course
    != pagy_bootstrap_nav(@pagy)
  %br

app/views/courses/new.html.haml
- content_for :title do
  University
  \|
  New Course

.card
  .card-body
    %h3
      .fa.fa-graduation-cap
        New course
  .card-body
    = render 'form'

= link_to 'Back', courses_path

app/views/courses/show.html.haml
- content_for :title do
  University
  \|
  = @course.title


= link_to 'Courses/', courses_path
= link_to @course.title, course_path(@course)
%p
.row
  .col-lg-8.order-1.order-lg-1
    .jumbotron
      %h3
        .fa.fa-graduation-cap
        = @course.title
      .p-3
      .row
      .fa.fa-clock
        = @course.updated_at.strftime("%b/%Y")
      .row
      .fa.fa-globe-africa
        = @course.language
      .row
      .fa.fa-signal
        = @course.level
      .p-3
      = @course.description

    %h4
      .fa.fa-tasks
        = pluralize(@course.lessons_count, 'lesson')

      .float-right
        .fa.fa-spinner
        = number_to_percentage(@course.progress(current_user), precision: 0)
      %h6.text-right
        = certificate_button(@course)

    %ul.list-group.lesson-sortable
      - @lessons.each do |lesson|
        = content_tag "div", id: "lesson-#{lesson.id}", data: { model_name: lesson.class.name.underscore, update_url: course_lesson_sort_path(@course, lesson)} do
          %li.list-group-item
            =  render "lessons/lesson_preview",  lesson: lesson

    %p
    %h4
      .fa.fa-comment
      = pluralize(@enrollments_with_reviews.count, 'review')

    - @enrollments_with_reviews.each do |enrollment|
      = render 'enrollments/enrollment', enrollment: enrollment
      %p
    %p
  .col-lg-4.order-0.order-lg-1
    .sticky-top
      = render 'courses/course', course: @course

%h4
  .fa.fa-clone
    Similar Courses
.col-md-10
  .card-columns
    - @courses.each do |course|
      = render 'courses/course', course: course